
package fr.polytechnancy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConversionService", targetNamespace = "http://www.polytechNancy.fr", wsdlLocation = "file:/Users/mac/IdeaProjects/ClientJava/src/ConversionService.wsdl")
public class ConversionService
    extends Service
{

    private final static URL CONVERSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERSIONSERVICE_EXCEPTION;
    private final static QName CONVERSIONSERVICE_QNAME = new QName("http://www.polytechNancy.fr", "ConversionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/mac/IdeaProjects/ClientJava/src/ConversionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERSIONSERVICE_WSDL_LOCATION = url;
        CONVERSIONSERVICE_EXCEPTION = e;
    }

    public ConversionService() {
        super(__getWsdlLocation(), CONVERSIONSERVICE_QNAME);
    }

    public ConversionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERSIONSERVICE_QNAME, features);
    }

    public ConversionService(URL wsdlLocation) {
        super(wsdlLocation, CONVERSIONSERVICE_QNAME);
    }

    public ConversionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERSIONSERVICE_QNAME, features);
    }

    public ConversionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConversionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Conversion
     */
    @WebEndpoint(name = "ConversionPort")
    public Conversion getConversionPort() {
        return super.getPort(new QName("http://www.polytechNancy.fr", "ConversionPort"), Conversion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Conversion
     */
    @WebEndpoint(name = "ConversionPort")
    public Conversion getConversionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytechNancy.fr", "ConversionPort"), Conversion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERSIONSERVICE_EXCEPTION!= null) {
            throw CONVERSIONSERVICE_EXCEPTION;
        }
        return CONVERSIONSERVICE_WSDL_LOCATION;
    }

}
